function(link_mkl visibility target_name)
    if(ENABLE_MKL)
      if(TARGET MKL::MKL)
          target_link_libraries(${target_name} ${visibility} MKL::MKL)
      else()
          target_include_directories(${target_name} ${visibility} ${MKL_INCLUDE_DIRS})
          target_link_libraries(${target_name} ${visibility} ${MKL_LIBRARIES})
          if(NOT MSVC)
              target_link_libraries(${target_name} ${visibility} pthread m dl)
          endif()
      endif()
    endif()
endfunction()
